### ISSUE TITLE
Card abstract

### ISSUE THREAD

**Issue by giacomodeliberali** [enricovettori93/Magic1PO#1]
Che sia il caso di rendere *abstract* il metodo `eseguiEffetto()` contenuto nella classe `Card`?
In modo da obbligare chi estende ad implementarlo?

**Comment by enricovettori93** [comment]
Può essere un idea. Oggi la questione dei mostri l'abbiamo accennata e fatto le classi per comodità di averle pronte, non abbiamo discusso riguardo i possibili effetti.
Se la facciamo abstract nel caso di un mostro senza effetto possiamo obbligare a implementare il lancio di un'eccezione tipo "throw noeffectmonster exception" (creando un eccezione personalizzata)

**Comment by giacomodeliberali** [comment]
Si esatto sei obbligato ad implementarlo, ma puoi lasciarlo vuoto. Mi piace anche la gestione di `TurnoNuovo` che mi sembra più modulabile dell'idea iniziale.

**Comment by enricovettori93** [comment]
Decisamente più comodo un arraylist di fasi, in modo da crearlo personalizzato in base agli effetti di gioco
