### ISSUE TITLE
Lista magie giocate/in campo

### ISSUE THREAD

**Issue by enricovettori93** [enricovettori93/Magic1PO#5]
Non ha senso tenere le magie che modificano gli attributi dei mostri dentro al campo, nella lista di magie in campo del giocatore si tengono solo gli incantesimi.

Implementato

**Comment by elenaross** [comment]
Quindi in campo teniamo una lista di Creature e una lista di Enchantment, gli Instant li gestiamo nello Stack e le Sorcery le risolviamo immediatamente (y)
